Module 1 Day 5 code warmup:
Practice:
1. Create a list with elements ranging from 1 to 10
2. Create an array with the shape (2, 3, 2)
3. Print the first row of the array
4. Challenge: Create a function that adds together two arrays
5. Challenge: Using `challenge_list = [1,2,3,4,5]`, create a new list that should equal `[0, 1, 2, 3, 6, 5, 12, 7, 20, 9]`
Hint1: Use a for loop!
Hint2: The first number in challenge_list is multiplied by its index to get the first number in the new_list. The first number in challenge_list is added to its index to get the second number in the new list. This repeats for each number in challenge_list.

Question:
What are some differences between a list and a numpy array?

In [2]:
elements_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
elements_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [18]:
a = np.array([[[1,2],[3, 4],[5, 6]], [[7, 8],[9, 10],[11,12]]])
print(a)
print(a.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


In [19]:
#Print the first row of the array
a

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [24]:
b = a[0:, 1]
b

array([[ 3,  4],
       [ 9, 10]])

In [25]:
b = a[1]
b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [26]:
b = a[0]
b

array([[1, 2],
       [3, 4],
       [5, 6]])

Challenge: Using `challenge_list = [1,2,3,4,5]`, create a new list that should equal `[0, 1, 2, 3, 6, 5, 12, 7, 20, 9]`
Hint1: Use a for loop!
Hint2: The first number in challenge_list is multiplied by its index to get the first number in the new_list. The first number in challenge_list is added to its index to get the second number in the new list. This repeats for each number in challenge_list.

Question:
What are some differences between a list and a numpy array?

In [38]:
#Copy from friend Christian
#def function():
 #  a + b  NOT DONE YET

challenge_list = [1,2,3,4,5]
newval= []
for i in range(len(challenge_list)):
   newval.append(challenge_list[i] * i)
   newval.append(challenge_list[i] + i)

print(newval)

[0, 1, 2, 3, 6, 5, 12, 7, 20, 9]


In [7]:
challenge_list = [1, 2, 3, 4, 5]
newval = []
for i in challenge_list:
   newval.append(i * (i - 1))
   newval.append(i + i - 1)

print(newval)

[0, 1, 2, 3, 6, 5, 12, 7, 20, 9]


In [9]:
challenge_list = [1, 2, 3, 4, 5]
newval = []
for i in challenge_list:
   newval.append(i * challenge_list.index(i))
   newval.append(i + challenge_list.index(i))

print(newval)

[0, 1, 2, 3, 6, 5, 12, 7, 20, 9]


In [37]:
range(len(challenge_list))

range(0, 5)

In [32]:
my_list = ['one', 'two', 'three', 'four', 'five']
my_list_len = len(my_list)
for i in range(0, my_list_len):
    print(my_list[i])


one
two
three
four
five


In [30]:
range(5)

range(0, 5)

In [31]:
print(range(5))

range(0, 5)
